### ISSUE TITLE
Wiki - two exact same pages: any usecase & compatible -> delete one

### ISSUE THREAD

**Issue by VicObee** [threefoldfoundation/info_threefold_pub#102]
https://library.threefold.me/info/threefold/#/cloudcompare/threefold__compatible

https://library.threefold.me/info/threefold/#/cloudcompare/threefold__no_redevelop

**Comment by samtaggart** [comment]
I believe this was done intentionally. It's using an include. Not a big enough issue to fix now but something to look into for future.
