### ISSUE TITLE
FreeFlow: 404 Error on several pages  

### ISSUE THREAD

**Issue by amandacaster** [threefoldfoundation/info_threefold_pub#105]
FreeFlow has a few links that are facing the 404 Error. 

https://threefoldfoundation.github.io/books/freeflow/network/farming/farming_intro.html
https://threefoldfoundation.github.io/books/freeflow/network/farming/farming_reward.html
https://threefoldfoundation.github.io/books/freeflow/network/buy/buy_my_chi.html
https://threefoldfoundation.github.io/books/freeflow/network/tokens/ffk.html
https://threefoldfoundation.github.io/books/freeflow/network/buy/buy_my_twin.html

All the above Pages are seen with the below screenshot

![image](https://user-images.githubusercontent.com/88147124/202395390-29d012e9-98f6-4259-ac92-ba477f8c452c.png)

**Comment by sasha-astiadi** [comment]
- [ ] HOMEPAGE change chi into TFT

- [ ] replace image from

![Image](https://github.com/threefoldfoundation/info_threefold_pub/assets/43240801/1ac56957-7f7e-41ee-8922-fbd568228c8a)

to:

[tf.png.zip](https://github.com/threefoldfoundation/info_threefold_pub/files/12161435/tf.png.zip)



- [ ] ACQUIRE

TFT
The digital energy currency of
the FreeFlow network `TFT`

- [ ] redir 'know more; on chi, to https://manual.grid.tf/threefold_token/threefold_token.html (open new tab)

**Comment by sasha-astiadi** [comment]
- [ ] #vision page
change button. link to mailto:info@myfreeflow.org

**Comment by sasha-astiadi** [comment]
- [ ] twin page

- [ ] change get the twin button URL to "mailto:info@myfreeflow.org"

- [ ]  Remove section
![Image](https://github.com/threefoldfoundation/info_threefold_pub/assets/43240801/8742a43c-3bee-4768-8ced-e866c81e46e9)

- [ ] replace architecture url to https://manual.grid.tf/intro/grid3_howitworks.html
- [ ] change get the twin button URL to "mailto:info@myfreeflow.org"

**Comment by sasha-astiadi** [comment]
node page:

- [ ] know more url replace to: https://manual.grid.tf/intro/grid3_howitworks.html#3nodes-unleashing-the-power-of-raw-capacity
- [ ] full details url replace to: https://manual.grid.tf/farmers/farmers.html
- [ ] see rewards button url replac to: https://manual.grid.tf/faq/faq.html?highlight=rewards#farming-rewards-and-related-notions

**Comment by sasha-astiadi** [comment]
experiences page

- [ ] see experiences button to demo.freeflow.life

**Comment by sasha-astiadi** [comment]
take part page:


- [ ] change chi into TFT

- [ ] replace image from

![Image](https://github.com/threefoldfoundation/info_threefold_pub/assets/43240801/1ac56957-7f7e-41ee-8922-fbd568228c8a)

to:

[tf.png.zip](https://github.com/threefoldfoundation/info_threefold_pub/files/12161435/tf.png.zip)



- [ ] ACQUIRE

TFT
The digital energy currency of
the FreeFlow network `TFT`

- [ ] redir 'know more; on chi, to https://manual.grid.tf/threefold_token/threefold_token.html (open new tab)

**Comment by ehab-hassan** [comment]
all fixed but there is no broken link on the vision page
![image](https://github.com/threefoldfoundation/info_threefold_pub/assets/10484295/505fe21e-1c99-4d33-afa7-80c14bb95cd7)
 which button u need to change?
