### ISSUE TITLE
Wiki - Mastodon Manual - Error Link - http://www.getmastodon.threefold.io/

### ISSUE THREAD

**Issue by TullysInc** [threefoldfoundation/info_threefold_pub#107]
http://www.getmastodon.threefold.io/ renders an error when attempting to access the link:

![Mastodon](https://user-images.githubusercontent.com/105203696/211849242-b988afdb-b261-43dc-8614-77e51e962918.jpg)

![image](https://user-images.githubusercontent.com/105203696/211849385-a3231a5a-2f83-472f-bf88-34486c54b81c.png)

**Comment by TullysInc** [comment]
Hello @sasha-astiadi  - I apologize I'm unable to assign you the ticket. Please have a look.

**Comment by sasha-astiadi** [comment]
done
