### ISSUE TITLE
Some token wiki pages need updating

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/info_threefold_pub#114]
- [ ] On https://library.threefold.me/info/threefold#/tokens/threefold__stats_special_wallets ... "Token Overview Farmed" and "Locked Tokens Overview" links are broken https://library.threefold.me/info/threefold#/tokens/threefold__stats_token_overview
- [ ] On https://library.threefold.me/info/threefold#/tokens/threefold__token_overview ... "Token Overview Farmed" and "Locked Tokens Overview" links are broken
- [ ] On https://library.threefold.me/info/threefold#/tokens/threefold__stats_token_overview ... "Total Token Overview" and "Token Overview Farmed" and "Locked Tokens Overview" links are broken
- [ ] On https://library.threefold.me/info/threefold#/tokens/threefold__tokenomics ... the Vesting Section needs to be modified / updated based on the unvesting
- [ ] As well as the https://library.threefold.me/info/threefold#/tokens/threefold__vesting_overview page

@sasha-astiadi Possible for you to handle this? If you need any help please ask or leave Kristof or Rob as reviewers.

**Comment by amandacaster** [comment]
https://library.threefold.me/info/threefold#/tokens/threefold__token_overview?id=threefold-token-overview - The locked tokens overview needs to be updated/changed as it is not opening but not able to find the info on the .md file to make changes.

![photo_2023-04-27_19-08-15](https://user-images.githubusercontent.com/88147124/234881240-bd5ad906-6175-45e8-9142-60d6b80b84ee.jpg)

**Comment by sasha-astiadi** [comment]
[Token Overview Farmed](https://library.threefold.me/info/threefold#/tokens/threefold__stats_token_overview_farmed)

[Locked Tokens Overview](https://library.threefold.me/info/threefold#/tokens/threefold__tokens_locked)

**Comment by samaradel** [comment]
cannot update wikis atm, got many errors while installing publishtools

**Comment by sasha-astiadi** [comment]
@samaradel no we no longer use publishtools for reviewing the changes... we can ask the ops to bring back www2 for review?

**Comment by samaradel** [comment]
> @samaradel no we no longer use publishtools for reviewing the changes... we can ask the ops to bring back www2 for review?

as per our discussion on telegram, we're blocked now

**Comment by sasha-astiadi** [comment]
@robvanmieghem do u know the codes to this pages?

**Comment by robvanmieghem** [comment]
no

**Comment by sasha-astiadi** [comment]
refer to new manual now
