### ISSUE TITLE
Update all links to the manual from the Library

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/info_threefold_pub#120]
Any manual link should point to https://manual.grid.tf/ – NOT https://library.threefold.me/info/manual/#/

- [x] In the dropdown under TF Grid Tools in top nav bar
- [x] Manual menu item on left sidebar
- [x] Need to do a search of all links throughout the Library and update them to the new manual

**Comment by samtaggart** [comment]
@amandacaster is this something you can help with? Let me know!

**Comment by amandacaster** [comment]
@samtaggart sure I can help with this.

**Comment by amandacaster** [comment]
@sasha-astiadi [PR](https://github.com/threefoldfoundation/info_threefold_pub/pull/123) created for the FAQ  navigation from the https://library.threefold.me/info/threefold#/

**Comment by sasha-astiadi** [comment]
https://github.com/threefoldfoundation/info_threefold_pub/blob/development/wiki/navbar_include.md

**Comment by amandacaster** [comment]
@sasha-astiadi manual link under the TF Grid Tools has been changed and [PR](https://github.com/threefoldfoundation/info_threefold_pub/pull/125) has been created.

**Comment by amandacaster** [comment]
> @sasha-astiadi made changes to the FAQ please find the [PR](https://github.com/threefoldfoundation/info_threefold_pub/pull/126)

@sasha-astiadi I think as long as one PR is opened for one document all change commits made is running under that one PR, I am unable to create new PR for each change.

**Comment by amandacaster** [comment]
@samtaggart I double-checked and the links have been updated.
