### ISSUE TITLE
Update values on pricing tables doc

### ISSUE THREAD

**Issue by renauter** [threefoldfoundation/info_threefold_pub#121]
I guess this page is not updated.

https://library.threefold.me/info/threefold#/tfgrid/farming/threefold__proof_of_capacity

![image](https://github.com/threefoldfoundation/info_manual3/assets/73958772/06a941f9-c02a-425c-8e40-1ed7287fac3e)

The values in pricing table do not correspond to what is effectively coded in TFChain and that reflects the specs here
https://docs.google.com/spreadsheets/d/1E6MpGs15h1_flyT5AtyKp1TixH1ILuGo5tzHdmjeYdQ/edit#gid=2014089775

ex:
I have in specs 
cu_price_value: 7,2 USD/month
su_price_value: 3,6 USD/month

Other remark:
Maybe showing the price in TFT is no the best strategy as the reference price for capacity unit is in USD and the TFT/USD rate keeps changing.

**Comment by sasha-astiadi** [comment]
the file name on wiki:

https://library.threefold.me/info/threefold#/tfgrid/farming/threefold__proof_of_capacity

found on: ../info_threefold_pub/wiki/tfgrid/farming/proof_of_capacity.md

## farming reward calculation (line 49)
found on: ../info_threefold_pub/wiki/tfgrid/farming/includes/farming_reward_calculation.md


which also includes:

!!!include:farming_reward_disclaimer

wiki/tfgrid/farming/includes/farming_reward_disclaimer.md

**Comment by sasha-astiadi** [comment]
thanks @renauter updating now

**Comment by renauter** [comment]
Great!
Prices in TFT should also be updated in regards to an updated TFT/USD rate

**Comment by sasha-astiadi** [comment]
maybe we should have a call to review all next monday @renauter

**Comment by sasha-astiadi** [comment]
https://github.com/threefoldfoundation/info_threefold_pub/blob/3.10.0/wiki/tfgrid/pricing/cloudunits_pricing.md?plain=1
