### ISSUE TITLE
QSFS: type error and repo not found

### ISSUE THREAD

**Issue by waleedhammam** [threefoldfoundation/info_threefold_pub#30]
In this part

![Screenshot from 2021-11-09 16-01-29](https://user-images.githubusercontent.com/10658229/140937736-81e557de-3896-4743-b58a-ce5809fcf393.png)

should be `quantum` and it redirects to https://github.com/threefoldtech/quantum_storage which is not found

**Comment by LeeSmet** [comment]
Closed in 63fd2ee
