### ISSUE TITLE
Update Docs: Missing wallet for already created farms

### ISSUE THREAD

**Issue by coesensbert** [threefoldfoundation/info_threefold_pub#34]
As @LeeSmet mentioned most of the farms created on testnet3 have no wallet address linked to them.

```
FreeFarm []
HobbesFarm [{TFT GDZQ42AAYDQN2LCDBJB66FWNLM4JXSKMWOAYW6OM7AFIYR4IDFEY33BQ}]
LinkmarkFarm []
GEC-Toronto1-testnet3 []
GEC-Rochester1-testnet3 []
GEC-Vienna1-testnet3 []
GEC-Vienna2-testnet3 []
GEC-Salzburg1-testnet3 []
GEC-Frankfurt1-testnet3 []
GEC-StGallen1-testnet3 []
test_farm_sameh [{TFT GDGSYZGVGFAFPBMLRTKNIO2JTNNHIQJXNPXF7MRS7FBQF57MIME6EZQD}]
Holistic-Computing-testFarm0001 [{TFT GC6NTUTV6ZGLW7QFGBCSJRMS6DJ5BKM2C67QHZLWL5D5UD64VRNRE5VQ}]
```

They possibly used this guide to create the farm: https://library.threefold.me/info/threefold#/manual_tfgrid3/threefold__create_farm_testnet

Which does not mention adding an address to the created farm.

**Comment by xmonader** [comment]
@gmachtel please update, all of GE farms won't get tokens like that

**Comment by gmachtel** [comment]
communicated to GE
For freefarm @coesensbert

**Comment by coesensbert** [comment]
Great, will do for Freefarm. Thx @gmachtel

**Comment by coesensbert** [comment]
For Freefarm with ID 1 on gridv3, used the same stellar address from v2: GDUKYVYPEENRASFPVLBDA7WUTSY3ZFWWOLNOHRJBWCWYPF5PH5IHSXLX

**Comment by gmachtel** [comment]
All farms with nodes have stellar addresses now
