### ISSUE TITLE
Grid Enhancement Proposal:  add starting consensus percentage

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldfoundation/info_threefold_pub#49]
In the [GEP](https://github.com/threefoldfoundation/info_threefold_pub/blob/1aabdc98e8638bf7c0a33c3d245ba4f49ac8a3ec/wiki/tfgrid/dao/gep.md)
is stated "when enough consensus is reached".  I think we should mentioned a starting figure (percentage) of this consensus figure.

**Comment by despiegk** [comment]
its completely variable and will be specified when specs ready

**Comment by samtaggart** [comment]
Updated to clarify, and closing this issue: https://github.com/threefoldfoundation/info_threefold_pub/commit/945a8c23a6c4570d1298e7473d902d99acb68b30
