### ISSUE TITLE
Change url pointing to Explore Documentation

### ISSUE THREAD

**Issue by Miket188** [threefoldfoundation/info_threefold_pub#52]
Have the url for the button Explore the Documentation on  https://threefold.io/developer point to the bit at the bottom of the page that says Explore Documentation, rather than a link directly to the docs.

In addition, import the three column navigation so that it's the first thing people see when they do get to the docs:https://library.threefold.me/info/threefold/#/

<img width="309" alt="Screen Shot 2022-01-14 at 1 20 38 PM" src="https://user-images.githubusercontent.com/64190175/149516756-6f98bee7-e502-4508-864b-64d9f8815f73.png">

<img width="1257" alt="Screen Shot 2022-01-14 at 1 20 59 PM" src="https://user-images.githubusercontent.com/64190175/149516748-f2cf2487-88c4-4007-9162-d9a14af5048f.png">

**Comment by Vilnite** [comment]
Website related point is assigned to web team on web circle:

https://circles.threefold.me/project/despiegk-product_web_threefold/us/252?milestone=193

**Comment by Vilnite** [comment]
Second point for library, I see it as a suggestion to change our navigation of a left side menu bar as that's pretty much what it is.

**Comment by sasha-astiadi** [comment]
explore doc button now redir to the three columns
