### ISSUE TITLE
Technology section issue 

### ISSUE THREAD

**Issue by AlexandreHannelas** [threefoldfoundation/info_threefold_pub#58]
There's an issue with the technology section on the wiki. 

Need to bring back technology in sidebar. Now, technology is in cloud sidebar and when clicking on Technology it only opens up the following: 
<img width="1438" alt="Screenshot 2022-02-09 at 15 10 19" src="https://user-images.githubusercontent.com/78421574/153217987-76673d42-50c0-42e6-b8c7-36f27b482958.png">
y

When clicking on Cloud Primitives Function it opens new window and opens technology section with sidebar etc. 

Please fix the above

**Comment by rkhamis** [comment]
obsolete
