### ISSUE TITLE
Updates to buy/sell TFT info

### ISSUE THREAD

**Issue by scottyeager** [threefoldfoundation/info_threefold_pub#66]
Some updates suggested to token section of the wiki:

1. There seems to no longer be a TFT/USD pair on BTC-Alpha. It's mentioned with a link at the bottom of [this page](https://library.threefold.me/info/threefold#/tokens/threefold__tft_btc_alpha)
2. Include StellarTerm as a Stellar DEX front end. It's the most simple I've found, requiring no install or account creation
3. Fix links, such as on [this page](https://library.threefold.me/info/threefold#/tokens/threefold__lobstr_wallet), which render as seen below:

```
Download the Lobstr app from the [Appstore](https://apps.apple.com/us/app/lobstr-stellar-wallet/id1404357892 ‘:ignore’ ‘:ignore’) or [Google Play](https://play.google.com/store/apps/details?id=com.lobstr.client&hl=nl ‘:ignore’ ‘:ignore’)
```

**Comment by samtaggart** [comment]
@nbabenko is working on number 2 and investigating number 1. I will handle number 3.

**Comment by scottyeager** [comment]
Great, thanks guys. I'd say lets also remove StellarX until/if we can get it whitelisted again.

**Comment by samtaggart** [comment]
1 and 3 handled, will be merged in today. Also removeid StellarX for now.

**Comment by samtaggart** [comment]
In addition, we made general improvements to the How to Buy & Sell section this week to get rid of Liquid and make things more clear for people.
