### ISSUE TITLE
Register status of outreach to stellar wallets and exchanges here so community can participate

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/info_threefold_pub#67]

**Comment by samtaggart** [comment]
@nbabenko Can you please update the description with the status for the various platforms?

**Comment by sasha-astiadi** [comment]
@nbabenko can you explain more about this story? do we still need it

**Comment by nbabenko** [comment]
done already, most of the wallets and exchanges already whitelisted TFT
