### ISSUE TITLE
Small improvements to How to Buy section

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/info_threefold_pub#72]
- [ ] **Solar Wallet**: Step 3 on creating an account could use more info (what are the steps for creating a new account or importing an existing account, and how do the steps differ?). The rest is clear to me.

- [ ] **LOBSTR Wallet**: Step 1 could use more details on what is needed / what to consider when creating an account. Is it also possible to import an existing account like with [Solar](https://library.threefold.me/info/threefold#/tokens/threefold__solar_wallet?id=important-instructions-to-secure-your-wallet)? If so, what are the steps? Also, add “Important instructions to secure your wallet” section, like it was done for Solar.

**Interstellar**:

- [ ] Part 2 has an error ("ThreeFold or Interstellar canâ€™t help anyone restore accounts or the funds attached to them in any case!") and a missing image ("![]img/interstellar_account_overview_1.jpg)").

- [ ] Part 4, second image: There is a lot going on in that image and users have to fill in different data for their order. I think it would be good to explain the different elements and to give an example for one specific order below that image.

- [ ] At the bottom, also add an “Important instructions to secure your wallet” section, like it was done for [Solar](https://library.threefold.me/info/threefold#/tokens/threefold__solar_wallet?id=important-instructions-to-secure-your-wallet).

- [ ] **1inch**: Add to step 4 that the default network is Ethereum and add an image of what the Ethereum button looks like to make it easier for people to find.

- [ ] **BTC-Alpha**: Doesn't show any images. Would be good to add a step-by-step image guide like the documentation on the other options provides – but only if we're keeping BTC-Alpha for a while. If we're planning to delist soon, it's not worth the work.

--

- [ ] I'd also change the link to the forum in the [Get Support](https://library.threefold.me/info/threefold#/tokens/threefold__how_to_buy?id=get-support) section (at the bottom of the page) from the general forum link to the [How to buy TFT](https://forum.threefold.io/c/threefold-token/getting-tft/33) forum section, so people looking for help directly end up in the right place.

- [ ] Get rid of multiple Stellar files

**Comment by sasha-astiadi** [comment]
done on manual.grid.tf
