### ISSUE TITLE
Improve the info / flow of getting TFT, storing TFT, and adding liquidity on Stellar

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/info_threefold_pub#73]
Need to execute on the proposal listed here: https://github.com/threefoldfoundation/info_threefold_pub/issues/68

Three sections:

- Get TFT (all the ways to buy TFT)
- Store TFT (wallets)
- Drive TFT Liquidity

Will review with @scottyeager before executing, and will do this on a separate branch.

Goal is to make the process as simple and clear as possible.

For reference: https://docs.google.com/spreadsheets/d/1Gv__q_R_PB0EAY-afgQ_lBhpoOxZKpzuZG_6-L4IFNo/edit#gid=0 

Notes from conversation with Scott:

- How to add liquidity via AMM and the benefits - as people add more liquidity, becomes more attractive to trade in large quantities, more fees, etc. If you're a holder, trade through stellar and provide liquidity.
- Might earn some yield, but mostly it's a nice way to support the project ... impermanent loss ...
- Explain that USDC is a good pool to be (versus XLM) in because of the stability of the token

**Comment by samtaggart** [comment]
Making progress here: https://github.com/threefoldfoundation/info_threefold_pub/tree/development_sam_token

**Comment by sasha-astiadi** [comment]
@samtaggart status?
