### ISSUE TITLE
Update Library docs: remove Portal, add Dashboard

### ISSUE THREAD

**Issue by coesensbert** [threefoldfoundation/info_threefold_pub#74]
The portal has been deprecated by now, everyone should use the dashboard, but there is almost no mention of it in our documentation. All the docs and screenshots still talk about the portal, which by now has been taken offline!

Please update all documentation to point to the dashboard https://dashboard.grid.tf/ for all nets + change the screenshots.
Some examples:

https://library.threefold.me/info/manual/#/getstarted/manual__tfchain_portal_polkadot_create_account
https://library.threefold.me/info/manual/#/getstarted/manual__tfchain_portal_ui_activation
https://library.threefold.me/info/manual/#/getstarted/manual__tfchain_portal_ui_tokens
https://library.threefold.me/info/manual/#/manual__tfchain_portal_home
..

**Comment by sasha-astiadi** [comment]
@rawdaGastan is this done?

**Comment by rawdaGastan** [comment]
@sasha-astiadi yes!
