### ISSUE TITLE
Tokens - Provide Liquidity for TFT - page is blank

### ISSUE THREAD

**Issue by amandacaster** [threefoldfoundation/info_threefold_pub#77]
The page is completely blank once you click on it also gives a shaky screen before it opens https://library.threefold.me/info/threefold#/tokens/threefold__tft_liquidity

![image](https://user-images.githubusercontent.com/88147124/195587611-0be6785b-2644-4a5f-89ba-d535930297ab.png)

**Comment by nbabenko** [comment]
submitted first version, @samtaggart can you please review?

**Comment by samtaggart** [comment]
On which branch?

**Comment by samtaggart** [comment]
Nevermind, I see it. It's good enough for now but we'll need to continue to improve over time. Thanks!

**Comment by samtaggart** [comment]
We'll get it updated today.
