### ISSUE TITLE
Hardware Options Page -- Link is sending to V2 explorer

### ISSUE THREAD

**Issue by Ashishban** [threefoldfoundation/info_threefold_pub#81]
The tag for explorer is linked to V2 explorer

Page - https://library.threefold.me/info/threefold/#/tfgrid/farming/threefold__farming_hardware_overview

![image](https://user-images.githubusercontent.com/91247662/195591390-bd3ac81b-c333-4305-bd75-180beff98822.png)

**Comment by samtaggart** [comment]
I fixed this link along with ThreeFold Node Shop (now goes to marketplace). I also replaced other old explorer links. Will be updated with next push.
