### ISSUE TITLE
L2 Validator page - No link

### ISSUE THREAD

**Issue by Ashishban** [threefoldfoundation/info_threefold_pub#82]
No link for Cosmos Chain

Page - https://library.threefold.me/info/threefold/#/decentralization/validators/threefold__validator_l2_details

![image](https://user-images.githubusercontent.com/91247662/195591574-efa285ce-8476-422c-8c97-23506ed46a55.png)

**Comment by sabrinasadik** [comment]
Not sure if needed, but please take a look @sasha-astiadi

**Comment by samtaggart** [comment]
Not needed.
