### ISSUE TITLE
Grid - Capacity Explorer - Link is sending to V2 explorer

### ISSUE THREAD

**Issue by Ashishban** [threefoldfoundation/info_threefold_pub#83]
In second para of Proof of Capacity ---> [ThreeFold Grid Capacity Explorer](http://explorer.grid.tf/)

Page - https://library.threefold.me/info/threefold/#/tfgrid/farming/threefold__proof_of_capacity

![image](https://user-images.githubusercontent.com/91247662/195591730-2b9bb99e-8bf4-46f4-bf2e-bc333fa0a54c.png)

**Comment by samtaggart** [comment]
Fixed, will be updated in next push.
