### ISSUE TITLE
Home Page of Library - Image Missing 

### ISSUE THREAD

**Issue by Ashishban** [threefoldfoundation/info_threefold_pub#85]
https://library.threefold.me/info/threefold/#/

![image](https://user-images.githubusercontent.com/91247662/195592123-e0c6b780-4630-4790-b61a-4b8979141faf.png)

**Comment by sasha-astiadi** [comment]
the file threefold_home is there, its also a technical issue i dont understand, will assign kds @despiegk

**Comment by sasha-astiadi** [comment]
@xmonader do u know how to fix this? i cant fix this one

**Comment by samtaggart** [comment]
Looks like this page is causing the issue: /Users/gosam/code/github/threefoldfoundation/info_threefold_pub/wiki/wethreepedia/wethreepedia_home/img/readme.md

**Comment by samtaggart** [comment]
Should go to this page: https://library.threefold.me/info/threefold#/threefold__threefold_home

**Comment by sasha-astiadi** [comment]
https://library.threefold.me/info/threefold#/ it works now
