### ISSUE TITLE
Link routing to V2 explorer (update required)- Decentralizatoin -> ThreeFold Companies

### ISSUE THREAD

**Issue by mahendravarmayadala93** [threefoldfoundation/info_threefold_pub#87]
![image](https://user-images.githubusercontent.com/89931135/195624034-802b87ed-9349-482f-b411-44d608e144b1.png)

Link : https://library.threefold.me/info/threefold/#/orgstructure/threefold__threefold_companies

**Comment by samtaggart** [comment]
I've updated this, will be pushed today

**Comment by samtaggart** [comment]
Also updated 600+ to 2,500+
