### ISSUE TITLE
Wiki_Legal > Disclaimer > Single Source of Truth: Github Repo link error

### ISSUE THREAD

**Issue by TullysInc** [threefoldfoundation/info_threefold_pub#91]
https://library.threefold.me/info/legal/#/legal__disclaimer > Single Source of Truth > Our single source of truth for our legal docs is stored on __Github__ : https://github.com/threefoldfoundation/legal/tree/master/src 

![image](https://user-images.githubusercontent.com/105203696/195659685-8e405964-5c97-44ac-b9f1-7caac070b4f5.png)

I presume it should be :  https://github.com/threefoldfoundation/info_legal/tree/master

**Comment by samtaggart** [comment]
Yes, I'm removing src. 👍

**Comment by sasha-astiadi** [comment]
fixed, asked the ops to update https://github.com/threefoldtech/tf_operations/issues/1230

**Comment by sasha-astiadi** [comment]
fixed on https://library.threefold.me/info/legal/#/legal__disclaimer
