### ISSUE TITLE
Wiki_Legal >Privacy Policy: http://allaboutcookies.org/ Access Denied

### ISSUE THREAD

**Issue by TullysInc** [threefoldfoundation/info_threefold_pub#92]
https://library.threefold.me/info/legal/#/legal__privacypolicy  
Privacy Policy > Cookies > For further information, visit: http://allaboutcookies.org/ 

Access Denied:
![image](https://user-images.githubusercontent.com/105203696/195660233-399f74b1-c0e9-4d41-af52-fef6338ddb2a.png)

**Comment by samtaggart** [comment]
Hmm, the site loads fine for me. Just checked with someone else in Europe. Maybe it's due to your country. Maybe it was an error? Will close for now.
