### ISSUE TITLE
Related website - Alliance consious internet (Main page) - Secure connnection failed.

### ISSUE THREAD

**Issue by mahendravarmayadala93** [threefoldfoundation/info_threefold_pub#93]
![image](https://user-images.githubusercontent.com/89931135/195662909-c428e748-8f14-446f-beb9-b16643e3c2b9.png)

By clicking on Alliance Consious internet redirects to https://consciousinternet.org/ but it shows an error like the below image

![image](https://user-images.githubusercontent.com/89931135/195663088-d08a3eda-48f7-44b5-bd59-1b427252e7b7.png)

**Comment by samtaggart** [comment]
Fixed on development. Removed completely.
