### ISSUE TITLE
BUILD button shows blank page on https://www.threefold.io/ 

### ISSUE THREAD

**Issue by mahendravarmayadala93** [threefoldfoundation/info_threefold_pub#94]
![image](https://user-images.githubusercontent.com/89931135/195682467-60f7f9b5-91ee-42fe-aaaa-0c2ae116d0e3.png)

Specific link:  https://www.threefold.io/cloud

**Comment by samtaggart** [comment]
Thanks for pointing this out, will be fixed today. It's already been pushed from my side.

Also please use the threefold website repo next time (https://github.com/threefoldfoundation/www_threefold_io)! 🙏
