### ISSUE TITLE
Wiki - Technology > Zero-OS primitives : repetition in every subsection

### ISSUE THREAD

**Issue by VicObee** [threefoldfoundation/info_threefold_pub#99]
Each of the 12 subsection repeats this section: 

<img width="958" alt="Screenshot 2022-10-14 at 11 42 45" src="https://user-images.githubusercontent.com/112857654/195816514-a7301448-54ac-49a2-8dff-6569a77583da.png">

Maybe better to mention it only once in the intro

**Comment by VicObee** [comment]
https://library.threefold.me/info/threefold#/technology/threefold__tfgrid_primitives

**Comment by samtaggart** [comment]
I think it's OK to have them on the sidebar, it was done intentionally. Let's not fix what's not broken 👍
